use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::commands::{
        history, keychain, learning_profile, notifications, preferences, quick_pane, recovery,
        screenshot, url_fetch,
    };

    Builder::<tauri::Wry>::new().commands(collect_commands![
        keychain::check_api_key_configured,
        keychain::save_api_key,
        keychain::load_api_key,
        keychain::remove_api_key,
        preferences::greet,
        preferences::load_preferences,
        preferences::save_preferences,
        notifications::send_native_notification,
        recovery::save_emergency_data,
        recovery::load_emergency_data,
        recovery::cleanup_old_recovery_files,
        quick_pane::show_quick_pane,
        quick_pane::dismiss_quick_pane,
        quick_pane::toggle_quick_pane,
        quick_pane::get_default_quick_pane_shortcut,
        quick_pane::update_quick_pane_shortcut,
        screenshot::capture_fullscreen,
        screenshot::check_screen_recording_permission,
        screenshot::open_screen_recording_settings,
        screenshot::start_area_selection,
        screenshot::complete_area_selection,
        screenshot::cancel_area_selection,
        screenshot::start_window_selection,
        screenshot::get_pending_window_bounds,
        screenshot::get_default_screenshot_shortcuts,
        screenshot::update_screenshot_shortcut,
        screenshot::check_accessibility_permission,
        screenshot::open_accessibility_settings,
        history::history_save_session,
        history::history_save_messages,
        history::history_list_sessions,
        history::history_load_session,
        history::history_delete_session,
        history::history_clear_all,
        history::history_search_sessions,
        history::history_cleanup_old_sessions,
        url_fetch::fetch_url_content,
        learning_profile::load_learning_profile,
        learning_profile::append_learning_profile_entry,
        learning_profile::delete_learning_profile_entry,
        learning_profile::clear_learning_profile,
    ])
}

/// Export TypeScript bindings to the frontend.
/// Run with: cargo test export_bindings -- --ignored
pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file.
    /// This test is ignored by default so it doesn't run in CI.
    /// Run manually with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
